name: PomafocusMac
options:
  bundleIdPrefix: com.staskus.pomafocus
  deploymentTarget:
    iOS: "17.0"

packages:
  PomafocusRoot:
    path: ../..

schemes:
  PomafocusMac:
    shared: true
    build:
      targets:
        PomafocusMac: all

targets:
  PomafocusMac:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: ../shared/Sources
    resources:
      - path: Sources/Assets.xcassets
    capabilities:
      push: true
      iCloud:
        containers:
          - iCloud.com.staskus.pomafocus
        services:
          - CloudKit
          - CloudDocuments
    dependencies:
      - package: PomafocusRoot
        product: PomafocusKit
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: PomafocusMac.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        PRODUCT_BUNDLE_IDENTIFIER: com.staskus.pomafocus.mac
        SWIFT_VERSION: "5.10"
        SWIFT_STRICT_CONCURRENCY: minimal
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        INFOPLIST_FILE: Info.plist
        INFOPLIST_KEY_PomafocusCloudKitContainer: iCloud.com.staskus.pomafocus
        INFOPLIST_KEY_PomafocusCloudKitEnabled: YES
        OTHER_LDFLAGS:
          - "-framework"
          - AppKit
          - "-framework"
          - Carbon
      configurations:
        Debug:
          INFOPLIST_KEY_PomafocusCloudKitEnabled: NO
        Release:
          INFOPLIST_KEY_PomafocusCloudKitEnabled: YES
