name: PomafocusMac
options:
  bundleIdPrefix: com.staskus.pomafocus
  deploymentTarget:
    macOS: "13.0"

packages:
  PomafocusRoot:
    path: ../..

schemes:
  PomafocusMac:
    shared: true
    build:
      targets:
        PomafocusMac: all

targets:
  PomafocusMac:
    type: application
    platform: macOS
    sources:
      - path: ../../Sources/Pomafocus
    resources:
      - path: ../../Resources
    capabilities:
      push: true
      iCloud:
        containers:
          - iCloud.com.staskus.pomafocus
        services:
          - CloudKit
          - CloudDocuments
    dependencies:
      - package: PomafocusRoot
        product: PomafocusKit
      - target: PomafocusHelper
    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: PomafocusMac.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        PRODUCT_BUNDLE_IDENTIFIER: com.staskus.pomafocus.mac
        SWIFT_VERSION: "5.10"
        SWIFT_STRICT_CONCURRENCY: minimal
        INFOPLIST_FILE: ../../Resources/Info.plist
        INFOPLIST_KEY_PomafocusCloudKitContainer: iCloud.com.staskus.pomafocus
        INFOPLIST_KEY_PomafocusCloudKitEnabled: YES
        MACOSX_DEPLOYMENT_TARGET: 13.0
        OTHER_LDFLAGS:
          - "-framework"
          - Carbon
    postBuildScripts:
      - name: Embed Privileged Helper
        script: |
          set -euo pipefail
          HELPER_NAME="com.staskus.pomafocus.mac.helper"
          HELPER_SRC="${BUILT_PRODUCTS_DIR}/${HELPER_NAME}"
          HELPER_DEST="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Library/PrivilegedHelperTools"
          LAUNCHD_DEST="${TARGET_BUILD_DIR}/${CONTENTS_FOLDER_PATH}/Library/LaunchServices"
          mkdir -p "${HELPER_DEST}" "${LAUNCHD_DEST}"
          cp -f "${HELPER_SRC}" "${HELPER_DEST}/${HELPER_NAME}"
          cp -f "${SRCROOT}/PrivilegedHelper/${HELPER_NAME}.plist" "${LAUNCHD_DEST}/${HELPER_NAME}.plist"
        shell: /bin/sh

  PomafocusHelper:
    type: tool
    platform: macOS
    sources:
      - path: ../../apps/macos/PrivilegedHelper
      - path: ../../Sources/PomafocusKit/Blocking/PrivilegedHelperProtocol.swift
    settings:
      base:
        PRODUCT_NAME: com.staskus.pomafocus.mac.helper
        PRODUCT_BUNDLE_IDENTIFIER: com.staskus.pomafocus.mac.helper
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        INFOPLIST_FILE: ../../apps/macos/PrivilegedHelper/Info.plist
