name: Pomafocus
options:
  bundleIdPrefix: com.staskus.pomafocus
  deploymentTarget:
    iOS: "18.0"

packages:
  PomafocusRoot:
    path: ../..

schemes:
  Pomafocus:
    shared: true
    build:
      targets:
        Pomafocus: all

targets:
  Pomafocus:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: ../shared/Sources
    capabilities:
      push: true
      iCloud:
        containers:
          - iCloud.com.staskus.pomafocus
        services:
          - CloudKit
          - CloudDocuments
      backgroundModes:
        - remote-notification
    dependencies:
      - package: PomafocusRoot
        product: PomafocusKit
      - target: PomafocusActivities
      - target: PomafocusShield
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        PRODUCT_BUNDLE_IDENTIFIER: com.povilasstaskus.pomafocus.ios
        SWIFT_VERSION: "5.10"
        SWIFT_STRICT_CONCURRENCY: minimal
        CODE_SIGN_ENTITLEMENTS: Pomafocus.entitlements
        INFOPLIST_FILE: Sources/Info.plist
        INFOPLIST_KEY_PomafocusCloudKitContainer: iCloud.com.staskus.pomafocus
        INFOPLIST_KEY_PomafocusCloudKitEnabled: YES
  PomafocusActivities:
    type: app-extension
    platform: iOS
    sources:
      - path: Widgets
    dependencies:
      - package: PomafocusRoot
        product: PomafocusKit
    settings:
      base:
        INFOPLIST_FILE: Widgets/Info.plist
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        CODE_SIGN_STYLE: Automatic
        SWIFT_STRICT_CONCURRENCY: minimal
        PRODUCT_BUNDLE_IDENTIFIER: com.povilasstaskus.pomafocus.ios.activities
    resources:
      - path: Sources/Assets.xcassets
  PomafocusShield:
    type: app-extension
    platform: iOS
    sources:
      - path: ShieldExtension
    settings:
      base:
        INFOPLIST_FILE: ShieldExtension/Info.plist
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        CODE_SIGN_STYLE: Automatic
        SWIFT_STRICT_CONCURRENCY: minimal
        PRODUCT_BUNDLE_IDENTIFIER: com.povilasstaskus.pomafocus.ios.shield
