name: Pomafocus
options:
  bundleIdPrefix: com.staskus.pomafocus
  deploymentTarget:
    iOS: "18.0"

packages:
  PomafocusRoot:
    path: ../..

schemes:
  Pomafocus:
    shared: true
    build:
      targets:
        Pomafocus: all

targets:
  Pomafocus:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: ../shared/Sources
    capabilities:
      push: true
      iCloud:
        containers:
          - iCloud.com.staskus.pomafocus
        services:
          - CloudKit
          - CloudDocuments
      backgroundModes:
        - remote-notification
    dependencies:
      - package: PomafocusRoot
        product: PomafocusKit
      - target: PomafocusActivities
      - target: PomafocusHomeWidgets
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        PRODUCT_BUNDLE_IDENTIFIER: com.povilasstaskus.pomafocus.ios
        SWIFT_VERSION: "5.10"
        SWIFT_STRICT_CONCURRENCY: minimal
        CODE_SIGN_ENTITLEMENTS: Pomafocus.entitlements
        INFOPLIST_FILE: Sources/Info.plist
        INFOPLIST_KEY_PomafocusCloudKitContainer: iCloud.com.staskus.pomafocus
        INFOPLIST_KEY_PomafocusCloudKitEnabled: YES
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "com.povilasstaskus.pomafocus.ios Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGN_ENTITLEMENTS: PomafocusAdHoc.entitlements
          PROVISIONING_PROFILE_SPECIFIER: "com.povilasstaskus.pomafocus.ios Ad Hoc"
  PomafocusActivities:
    type: app-extension
    platform: iOS
    sources:
      - path: Widgets
    dependencies:
      - package: PomafocusRoot
        product: PomafocusKit
    settings:
      base:
        INFOPLIST_FILE: Widgets/Info.plist
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        CODE_SIGN_STYLE: Manual
        SWIFT_STRICT_CONCURRENCY: minimal
        PRODUCT_BUNDLE_IDENTIFIER: com.povilasstaskus.pomafocus.ios.activities
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "com.povilasstaskus.pomafocus.ios.activities Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "com.povilasstaskus.pomafocus.ios.activities Ad Hoc"
    resources:
      - path: Sources/Assets.xcassets
  PomafocusHomeWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: HomeWidgets
        excludes:
          - "*.entitlements"
    dependencies:
      - package: PomafocusRoot
        product: PomafocusWidgetKit
    settings:
      base:
        INFOPLIST_FILE: HomeWidgets/Info.plist
        DEVELOPMENT_TEAM: L4KYCD4RPZ
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_ENTITLEMENTS: HomeWidgets/HomeWidgets.entitlements
        SWIFT_STRICT_CONCURRENCY: minimal
        PRODUCT_BUNDLE_IDENTIFIER: com.povilasstaskus.pomafocus.ios.homewidgets
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "Apple Development"
          PROVISIONING_PROFILE_SPECIFIER: "com.povilasstaskus.pomafocus.ios.homewidgets Development"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "com.povilasstaskus.pomafocus.ios.homewidgets Ad Hoc"
    resources:
      - path: Sources/Assets.xcassets
